### ISSUE TITLE
500 Internal error

### ISSUE THREAD

**Issue by bianjiang** [komoot/photon#130]
Try to use the existing index from http://photon.komoot.de/data/photon_data_140706.tar.bz2, but it gives 500 Internal error when calling the api. 

The search index from http://photon.komoot.de/data/photon_data_140706.tar.bz2 is invalid?

Tried on two different machines. Both Mac through.

Thanks,

**Comment by fire-stone** [comment]
Hello I have the same error. I find under `elasticsearch\data` also two folders `nodes` and `photon`. 
I'm currently under windows. I have downloaded the photon-db-latest. I use the photon-0.2.7.jar File.
Here is the full error when I'm trying to display http://localhost:2322/api?q=berlin:

[qtp378994577-115] ERROR spark.webserver.MatcherFilter -
org.elasticsearch.indices.IndexMissingException: [photon] missing
        at org.elasticsearch.cluster.metadata.MetaData.convertFromWildcards(MetaData.java:884)
        at org.elasticsearch.cluster.metadata.MetaData.concreteIndices(MetaData.java:692)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.<init>(TransportSearchTypeAction.java:118)
        at org.elasticsearch.action.search.type.TransportSearchQueryAndFetchAction$AsyncAction.<init>(TransportSearchQueryAndFetchAction.java:63)
        at org.elasticsearch.action.search.type.TransportSearchQueryAndFetchAction$AsyncAction.<init>(TransportSearchQueryAndFetchAction.java:60)
        at org.elasticsearch.action.search.type.TransportSearchQueryAndFetchAction.doExecute(TransportSearchQueryAndFetchAction.java:57)
        at org.elasticsearch.action.search.type.TransportSearchQueryAndFetchAction.doExecute(TransportSearchQueryAndFetchAction.java:47)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:104)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:43)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
        at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
        at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:338)
        at org.elasticsearch.action.search.SearchRequestBuilder.doExecute(SearchRequestBuilder.java:1112)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
        at de.komoot.photon.searcher.BaseElasticsearchSearcher.search(BaseElasticsearchSearcher.java:29)
        at de.komoot.photon.searcher.AbstractPhotonRequestHandler.handle(AbstractPhotonRequestHandler.java:26)
        at de.komoot.photon.SearchRequestHandler.handle(SearchRequestHandler.java:48)
        at de.komoot.photon.SearchRequestHandler.handle(SearchRequestHandler.java:24)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:139)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:54)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:451)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
        at java.lang.Thread.run(Unknown Source)

I'm using Win10.

**Comment by karussell** [comment]
For questions please use the mailing list. Please use photon-0.3-alpha1.jar for db-latest.

**Comment by fire-stone** [comment]
When I'm using photon-0.3-alpha1.jar I'm getting this error:

> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
Exception in thread "main" java.lang.IllegalArgumentException: property [elasticsearch.version] is missing for plugin [head]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:135)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:331)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:130)
        at org.elasticsearch.node.Node.<init>(Node.java:312)
        at de.komoot.photon.elasticsearch.Server$MyNode.<init>(Server.java:59)
        at de.komoot.photon.elasticsearch.Server.start(Server.java:119)
        at de.komoot.photon.App.main(App.java:52)

**Comment by karussell** [comment]
Sorry for this. Can you please try the freshly release photon-0.3-beta2.jar?

And if you try please use a data dir that contains the photon_data

java -jar photon-0.3-beta2.jar -data-dir download

**Comment by fire-stone** [comment]
My Database is in folder here: `C:\users\desktop\photon\` and there is the folder `photon_data`. I also saved there the .jar file. Here is the new error I get:

`[qtp1831812945-60] ERROR spark.http.matching.GeneralError -
org.elasticsearch.index.IndexNotFoundException: no such index
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.infe(IndexNameExpressionResolver.java:676) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:630) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:578) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:168) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:140) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:263) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:186) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:65) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:142) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:84) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80) ~[photon-0.3-beta2.jar:?]
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54) ~[photon-0.3-beta2.jar:?]
        at de.komoot.photon.searcher.BaseElasticsearchSearcher.search(BaseElasticsearchSearcher.java:28) ~[photon-0.3-beta2.jar:?]
        at de.komoot.photon.searcher.AbstractPhotonRequestHandler.handle(AbstractPhotonRequestHandler.java:28) ~[photon-0.3-beta2.jar:?]
        at de.komoot.photon.SearchRequestHandler.handle(SearchRequestHandler.java:50) ~[photon-0.3-beta2.jar:?]
        at de.komoot.photon.SearchRequestHandler.handle(SearchRequestHandler.java:26) ~[photon-0.3-beta2.jar:?]
        at spark.RouteImpl$1.handle(RouteImpl.java:72) ~[photon-0.3-beta2.jar:?]
        at spark.http.matching.Routes.execute(Routes.java:61) ~[photon-0.3-beta2.jar:?]
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130) [photon-0.3-beta2.jar:?]
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.server.Server.handle(Server.java:564) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673) [photon-0.3-beta2.jar:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591) [photon-0.3-beta2.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]`

**Comment by karussell** [comment]
How large is your photon_data folder?

**Comment by fire-stone** [comment]
98.5 GB

**Comment by karussell** [comment]
Strange. Maybe our import went wrong. What if you add `-cluster elasticsearch`?

**Comment by fire-stone** [comment]
If i add this I'll get the same error as above.

**Comment by karussell** [comment]
Ok, let me try this from scratch. What JDK and OS do you have?

**Comment by fire-stone** [comment]
Java Version 8 Update 162

OS = Windows 10

**Comment by karussell** [comment]
Can you try the smaller area that worked for me:

```bash
wget -O - http://download1.graphhopper.com/public/photon-db-nl-180122.tar.bz2 | bzip2 -cd | tar x
java -jar path/photon-0.3-beta2.jar 
```

**Comment by fire-stone** [comment]
It works. With the smaller area it works.

**Comment by karussell** [comment]
Can you try to re-download the world wide data?

**Comment by fire-stone** [comment]
I'll do that tomorow cause downloading the whole area lasts 4-5 hours.

**Comment by fire-stone** [comment]
So I have redownloaded it over night and it works fine now. Again thank you for the time!!!

**Comment by karussell** [comment]
Thanks for your confirmation! (It could be that the old version somehow corrupted the files or that the download was not 100% complete somehow)
