### ISSUE TITLE
Fresh install on Debian 7

### ISSUE THREAD

**Issue by denok-sri** [komoot/photon#156]
Hi,

I'm new to OSM and geocoding, followed install instructions from Readme, 

    # java -version
    java version "1.7.0_75"
    OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
    OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

    # cat /etc/debian_version
    jessie/sid

But http://photon.komoot.de/data/photon_data_021_150112.tar.bz2 is taking too long to download so I searched for more suitable and small data for  me http://download.geofabrik.de/europe/moldova-latest.osm.pbf *(is it correct format?)*

When I start photon (first run): 

    java -jar photon-0.2.2.jar

I get 

    # java -jar photon-0.2.2.jar
Trying jar:file:/tmp/photon/photon-0.2.2.jar!/elasticsearch-wordending-tokenfilter-0.0.1.zip...
Downloading .DONE
Installed ybon/elasticsearch-wordending-tokenfilter/0.0.1 into /tmp/photon/photon_data/elasticsearch/plugins/wordending-tokenfilter
Trying https://github.com/mobz/elasticsearch-head/archive/master.zip...
Downloading ..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Installed mobz/elasticsearch-head into /tmp/photon/photon_data/elasticsearch/plugins/head
Identified as a _site plugin, moving to _site structure ...
Installed mobz/elasticsearch-head into /tmp/photon/photon_data/elasticsearch/plugins/head/_site
Trying https://github.com/polyfractal/elasticsearch-inquisitor/archive/master.zip...
Downloading ...........................................................................................................................................................DONE
Installed polyfractal/elasticsearch-inquisitor into /tmp/photon/photon_data/elasticsearch/plugins/inquisitor
[main] INFO org.elasticsearch.node - [Atalon] version[1.4.1], pid[27470], build[89d3241/2014-11-26T15:49:29Z]
[main] INFO org.elasticsearch.node - [Atalon] initializing ...
[main] INFO org.elasticsearch.plugins - [Atalon] loaded [lang-mvel, wordending], sites [inquisitor, head]
[main] INFO org.elasticsearch.script - [Atalon] compiling script file [/tmp/photon/photon_data/elasticsearch/config/scripts/general-score.mvel]
[main] INFO org.elasticsearch.script - [Atalon] compiling script file [/tmp/photon/photon_data/elasticsearch/config/scripts/location-biased-score.mvel]
[main] INFO org.elasticsearch.node - [Atalon] initialized
[main] INFO org.elasticsearch.node - [Atalon] starting ...
[main] INFO org.elasticsearch.transport - [Atalon] bound_address {inet[/127.0.0.1:9301]}, publish_address {inet[/127.0.0.1:9301]}
[main] INFO org.elasticsearch.discovery - [Atalon] photon/nHaoK-MbR5WB9vfz2zt01A
[elasticsearch[Atalon][clusterService#updateTask][T#1]] INFO org.elasticsearch.cluster.service - [Atalon] new_master [Atalon][nHaoK-MbR5WB9vfz2zt01A][fe][inet[/127.0.0.1:9301]], reason: zen-disco-join (elected_as_master)
[main] INFO org.elasticsearch.http - [Atalon] bound_address {inet[/127.0.0.1:9201]}, publish_address {inet[/127.0.0.1:9201]}
[main] INFO org.elasticsearch.node - [Atalon] started
[main] INFO de.komoot.photon.elasticsearch.Server - started elastic search node
[elasticsearch[Atalon][clusterService#updateTask][T#1]] INFO org.elasticsearch.gateway - [Atalon] recovered [0] indices into cluster_state
== Spark has ignited ...
>> Listening on 0.0.0.0:2322
[Thread-4] INFO org.eclipse.jetty.server.Server - jetty-9.0.z-SNAPSHOT
[Thread-4] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@75821e76{HTTP/1.1}{0.0.0.0:2322}
[qtp1889207554-43] ERROR spark.webserver.MatcherFilter -
org.elasticsearch.indices.IndexMissingException: [photon] missing
        at org.elasticsearch.cluster.metadata.MetaData.convertFromWildcards(MetaData.java:828)
        at org.elasticsearch.cluster.metadata.MetaData.concreteIndices(MetaData.java:685)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.<init>(TransportSearchTypeAction.java:113)
        at org.elasticsearch.action.search.type.TransportSearchQueryAndFetchAction$AsyncAction.<init>(TransportSearchQueryAndFetchAction.java:61)
        at org.elasticsearch.action.search.type.TransportSearchQueryAndFetchAction$AsyncAction.<init>(TransportSearchQueryAndFetchAction.java:58)
        at org.elasticsearch.action.search.type.TransportSearchQueryAndFetchAction.doExecute(TransportSearchQueryAndFetchAction.java:55)
        at org.elasticsearch.action.search.type.TransportSearchQueryAndFetchAction.doExecute(TransportSearchQueryAndFetchAction.java:45)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:107)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:45)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
        at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
        at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:334)
        at org.elasticsearch.action.search.SearchRequestBuilder.doExecute(SearchRequestBuilder.java:1116)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
        at de.komoot.photon.searcher.BaseElasticsearchSearcher.search(BaseElasticsearchSearcher.java:18)
        at de.komoot.photon.searcher.AbstractPhotonRequestHandler.handle(AbstractPhotonRequestHandler.java:22)
        at de.komoot.photon.SearchRequestHandler.handle(SearchRequestHandler.java:44)
        at de.komoot.photon.SearchRequestHandler.handle(SearchRequestHandler.java:22)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:139)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:54)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:451)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
        at java.lang.Thread.run(Thread.java:745)

on trying to access localhost:2322/api?q=chisinau

What am I doing wrong?

**Comment by sdole** [comment]
The file you downloaded from geofabrik looks like the raw osm data. The
file you found slow to download is the elastic search index exported from
nominatim index of the world map. Photon will work only with an elastic
search index.

**Comment by denok-sri** [comment]
Thanks!

Is there a recommended way to convert raw osm data for specific country to the elastic search index? Or maybe I can find prepared elastic search indexes somewhere?

P.S. Another thing that is not clear to me is (from Readme):
    Once you have your nominatim database ready, you can import the data to photon:

How should I setup nominatim db? Any general guidance here?

**Comment by sdole** [comment]
See answers below.

On Wed, Mar 11, 2015 at 4:11 PM, denok-sri <notifications@github.com> wrote:

> Thanks!
>
> Is there a recommended way to convert raw osm data for specific country to
> the elastic search index? Or maybe I can find prepared elastic search
> indexes somewhere?
>
AFAIK, the only way to create the index is to export from nominatim. I dont
know if others have created and index that fulfils your requriements.

> P.S. Another thing that is not clear to me is (from Readme):
> Once you have your nominatim database ready, you can import the data to
> photon:
>
> How should I setup nominatim db? Any general guidance here?
>
there may be more than a handful ways to setup nominatim, but, OSM wiki has
the official guide
<http://wiki.openstreetmap.org/wiki/Nominatim/Installation>.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/komoot/photon/issues/156#issuecomment-78372670>.
>



-- 
President  |  Genvega Inc.  |  www.genvega.com  |  tel: 630.290.2561
