### ISSUE TITLE
QUESTIONS

### ISSUE THREAD

**Issue by MarcelPitch** [komoot/photon#157]
Hi,

Just few general questions about photon :

1. Is it possible to request **photon** directly with `osm_id`, in order to retrieve a place ?

2. Is it possible to filter the json result with only few properties (e.g `name` & `country`) ?

3. Is it possible to configure the provided ES for directly requesting it from another server ? 
I explain :
-> our **web server** is on 192.168.1.10
-> **photon** is on 192.168.1.11
The web server wants to request *ES*. But currently, *ES* (on *:9200*) is only listening on *localhost*.

Thanks !!!

**Comment by christophlingg** [comment]
1. that's not implemented but could ask elastic search for it, we are already indexing osm_id
2. you country=Austria for example? No, that's not possible, sdole implemented a filter on osm tag
3. if i got you right, karusell implemented this some days ago: https://github.com/komoot/photon/pull/144

**Comment by MarcelPitch** [comment]
OK @christophlingg,

Great !!! 

I download the latest snapshot.

Have a nice day !!!

**Comment by MarcelPitch** [comment]
@christophlingg,

(sorry) I don't understand how to use `-transport-addresses`.

So, please let me explain more concretely the environment I wish :

![photon](https://cloud.githubusercontent.com/assets/7402969/6614756/c44cbff6-c89d-11e4-8e94-265f893b9573.PNG)

**web-server** and **photon-server** are in same local network.

1. **client** request *Photon* in order to retrieve place
2. **client** get the complete place JSON and send the `osm_id` to **web-server**
3. **web-server** get the `osm_id` and request directly *ES* with it, in order to retrieve the place & country labels

So, no problem for 1. & 2. steps, but at the moment, **web-server** cannot access *ES* on **photon-server**. Only local queries can be done on *ES*.

I try to add the `-transport-addresses` when starting *Photon*, but no response when I try to request  from **web-server** :
```
http://192.168.1.11:9200
```

Could you help me on this ?

**Comment by karussell** [comment]
The transport client uses the java not the http port e.g. `-transport-addresses someip:9300`

**Comment by MarcelPitch** [comment]
Hi @karussell,

Thanks for your answer !

OK, so if I correctly understand, I have to start my Photon server as follows :
```
java -jar photon-0.2.2.jar -transport-addresses 192.168.1.11:9300
```

Right ?

**Comment by MarcelPitch** [comment]
Hi,

I come back to you for my usecase !

I've run the **photon-server** with this command :

```
java -jar photon-0.2.2.jar -transport-addresses 192.168.1.11:9300
```

Now, when I send a request from **web-server** (192.168.1.10) as follows :

```
http://192.168.1.11:2322/api?q=berlin
```

the **photon-server** returns this error : 
```
[qtp310897065-22] ERROR spark.webserver.MatcherFilter -
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:278)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:197)
        at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106)
        at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:334)
        at org.elasticsearch.client.transport.TransportClient.search(TransportClient.java:424)
        at org.elasticsearch.action.search.SearchRequestBuilder.doExecute(SearchRequestBuilder.java:1116)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
        at de.komoot.photon.searcher.BaseElasticsearchSearcher.search(BaseElasticsearchSearcher.java:18)
        at de.komoot.photon.searcher.AbstractPhotonRequestHandler.handle(AbstractPhotonRequestHandler.java:22)
        at de.komoot.photon.SearchRequestHandler.handle(SearchRequestHandler.java:44)
        at de.komoot.photon.SearchRequestHandler.handle(SearchRequestHandler.java:22)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:139)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:54)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:451)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
        at java.lang.Thread.run(Thread.java:745)
```

Moreover, on the **photon-server** (192.168.1.11), I cannot access the *ES head* plugin with this url :

```
http://localhost:9200/_plugin/head/
```

Is there any config I missed ?

Thanks !!!

**Comment by MarcelPitch** [comment]
Hi,

I wish to up this post.

Do you have any idea ? All help would be great !!! :smile: 

Have a nice day !

**Comment by christophlingg** [comment]
I can't help you with the TransportClient, that's something @karussell knows about

**Comment by christophlingg** [comment]
could you manage to make it work?

**Comment by MarcelPitch** [comment]
Hello @christophlingg,

I was working on another part of the project.

But, during my last tries, no, I didn't. But I was about to come back to @karussell, to know if he could help on this.

Thanks for your question.

**Comment by avently** [comment]
@christophlingg
that's not implemented but could ask elastic search for it, we are already indexing osm_id

Can you please implement it?
I don't know Java...
This feature (search by osm_id) is needed by many users of Photon.

**Comment by MarcelPitch** [comment]
Hi @avently,

Yes, as shown in my schema, I'd like to ask ES with an `osm_id`. 

My problem is to ask ES from another server. I cannot access the server and didn't manage to make `transport-adresses` work.

But if it cloud be directly implemented in photon, it would be great !!!

**Comment by MarcelPitch** [comment]
Hi @christophlingg, @karussell,

I come back to you for my environment problem : 

![photon](https://cloud.githubusercontent.com/assets/7402969/6614756/c44cbff6-c89d-11e4-8e94-265f893b9573.PNG)

Can I do this work with a *standard* photon ? If so, how can I do it ?

Or may be, I have to install my own Elastic Search server ?

A secondary question is about what @avently posted : Requesting Photon by osm_id. Did you plan it or is it totally not expected ?

Thanks for your answer and have a nice day !!!

**Comment by christophlingg** [comment]
@MarcelPitch i can't help you with your specific questions about your environment

I am not planning to introduce the feature of allowing quering osm ids, sorry but I have a lot of other projects running. Maybe asking nominatim via its API is an option?

**Comment by avently** [comment]
You can use Pelias. It's more powerful solution and it is supporting hard

**Comment by MarcelPitch** [comment]
Hi @christophlingg, @avently,

OK @christophlingg, no problem. Good luck for all your projects !!!

OK, @avently, thanks ! I'll check that !

Have a nice day !
