### ISSUE TITLE
exceptions.IndexError when location text actually lists multiple locations

### ISSUE THREAD

**Issue by paulborza** [komoot/photon#200]
'job_location': u'San Francisco, Singapore, Glasgow',
	 'job_location_type': 'Site',
	 'job_title': u'Internship: Computer Science',
	 'job_type': 'Internship',
	 'job_url': u'http://spire.com/careers/?gh_jid=19705',
	 'startup_id': 'spire'}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/site-packages/scrapy/middleware.py", line 62, in _process_chain
	    return process_chain(self.methods[methodname], obj, *args)
	  File "/usr/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 65, in process_chain
	    d.callback(input)
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 383, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "test.py", line 174, in process_item
	    location = geolocator.geocode(item['job_location'])
	  File "/usr/local/lib/python2.7/site-packages/geopy/geocoders/photon.py", line 133, in geocode
	    exactly_one
	  File "/usr/local/lib/python2.7/site-packages/geopy/geocoders/photon.py", line 202, in _parse_json
	    return cls.parse_resource(resources['features'][0])
	exceptions.IndexError: list index out of range

**Comment by paulborza** [comment]
My bad, this is a problem with the Geopy implementation not Photon itself.

**Comment by paulborza** [comment]
Opened bug for Geopy at https://github.com/geopy/geopy/issues/161
