### ISSUE TITLE
GroovyScriptExecutionException NullPointerException for q=sta and lat/lon

### ISSUE THREAD

**Issue by karussell** [komoot/photon#208]
As reported on the mailing list 'sta' and any lat/lon point triggers an exception, also on the most recent index:

```bash
[qtp1534873012-52079] ERROR spark.webserver.MatcherFilter - 
org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query_fetch], all shards failed; shardFailures {[yj72RYXES0eHbNYEWLbyXQ][photon][0]: QueryPhaseExecutionException[[photon][0]: query[filtered(function score (+((collector.default:sta~1 collector.de.ngrams:sta~1)~1) name.de.raw:sta^200.0 collector.de.raw:sta^100.0, functions: [{filter(*:*), function [script[1 + doc['importance'].value * 100], params [null]]}{filter(*:*), function [script[dist = doc['coordinate'].distanceInKm(lat, lon); 2 / (1.0 + dist / 40.0)], params [{lon=125.395057, lat=6.786715}]]}]))->cache(NotFilter(cache(BooleanFilter(_field_names:housenumber)))) QueryWrapperFilter(housenumber:sta) cache(BooleanFilter(_field_names:name.de.raw))],from[0],size[6]: Query Failed [Failed to execute main query]]; nested: GroovyScriptExecutionException[NullPointerException[null]]; }{[yj72RYXES0eHbNYEWLbyXQ][photon][1]: QueryPhaseExecutionException[[photon][1]: query[filtered(function score (+((collector.default:sta~1 collector.de.ngrams:sta~1)~1) name.de.raw:sta^200.0 collector.de.raw:sta^100.0, functions: [{filter(*:*), function [script[1 + doc['importance'].value * 100], params [null]]}{filter(*:*), function [script[dist = doc['coordinate'].distanceInKm(lat, lon); 2 / (1.0 + dist / 40.0)], params [{lon=125.395057, lat=6.786715}]]}]))->cache(NotFilter(cache(BooleanFilter(_field_names:housenumber)))) QueryWrapperFilter(housenumber:sta) cache(BooleanFilter(_field_names:name.de.raw))],from[0],size[6]: Query Failed [Failed to execute main query]]; nested: GroovyScriptExecutionException[NullPointerException[null]]; }{[yj72RYXES0eHbNYEWLbyXQ][photon][2]: QueryPhaseExecutionException[[photon][2]: query[filtered(function score (+((collector.default:sta~1 collector.de.ngrams:sta~1)~1) name.de.raw:sta^200.0 collector.de.raw:sta^100.0, functions: [{filter(*:*), function [script[1 + doc['importance'].value * 100], params [null]]}{filter(*:*), function [script[dist = doc['coordinate'].distanceInKm(lat, lon); 2 / (1.0 + dist / 40.0)], params [{lon=125.395057, lat=6.786715}]]}]))->cache(NotFilter(cache(BooleanFilter(_field_names:housenumber)))) QueryWrapperFilter(housenumber:sta) cache(BooleanFilter(_field_names:name.de.raw))],from[0],size[6]: Query Failed [Failed to execute main query]]; nested: GroovyScriptExecutionException[NullPointerException[null]]; }{[yj72RYXES0eHbNYEWLbyXQ][photon][3]: QueryPhaseExecutionException[[photon][3]: query[filtered(function score (+((collector.default:sta~1 collector.de.ngrams:sta~1)~1) name.de.raw:sta^200.0 collector.de.raw:sta^100.0, functions: [{filter(*:*), function [script[1 + doc['importance'].value * 100], params [null]]}{filter(*:*), function [script[dist = doc['coordinate'].distanceInKm(lat, lon); 2 / (1.0 + dist / 40.0)], params [{lon=125.395057, lat=6.786715}]]}]))->cache(NotFilter(cache(BooleanFilter(_field_names:housenumber)))) QueryWrapperFilter(housenumber:sta) cache(BooleanFilter(_field_names:name.de.raw))],from[0],size[6]: Query Failed [Failed to execute main query]]; nested: GroovyScriptExecutionException[NullPointerException[null]]; }{[yj72RYXES0eHbNYEWLbyXQ][photon][4]: QueryPhaseExecutionException[[photon][4]: query[filtered(function score (+((collector.default:sta~1 collector.de.ngrams:sta~1)~1) name.de.raw:sta^200.0 collector.de.raw:sta^100.0, functions: [{filter(*:*), function [script[1 + doc['importance'].value * 100], params [null]]}{filter(*:*), function [script[dist = doc['coordinate'].distanceInKm(lat, lon); 2 / (1.0 + dist / 40.0)], params [{lon=125.395057, lat=6.786715}]]}]))->cache(NotFilter(cache(BooleanFilter(_field_names:housenumber)))) QueryWrapperFilter(housenumber:sta) cache(BooleanFilter(_field_names:name.de.raw))],from[0],size[6]: Query Failed [Failed to execute main query]]; nested: GroovyScriptExecutionException[NullPointerException[null]]; }
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:237)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:183)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:565)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by karussell** [comment]
Sorry, is very likely a duplicate of #207
