### ISSUE TITLE
First Installation Failure

### ISSUE THREAD

**Issue by ralonso75** [komoot/photon#262]
Hi,

I'm trying to test your software, and I have several issues in Ms Windows environment.
steps:
1.- download photon-0.2.7.jar
2.- download photon-db-171026.tar.bz2
3.- using WinRar... uncompress photon-db-171026.tar.bz2 and the final folder/files structure is in the same folder:
photon-0.2.7.jar
photon_data
4.- I had to create a folder called Photon in "photon_data\elasticsearch\data\photon" and had to move the nodes folder inside photon because the index database could not be found.
4.- run in cmd "C:\Program Files (x86)\Java\jre1.8.0_111\bin\java" -jar photon-0.2.7.jar

this is the console log... (Could you help me to fix the problem?)

Trying jar:file:/F:/PHOTON/photon-0.2.7.jar!/elasticsearch-wordending-tokenfilter-0.0.1.zip...
Downloading .DONE
Installed ybon/elasticsearch-wordending-tokenfilter/0.0.1 into f:\PHOTON\photon_data\elasticsearch\plugins\wordending-tokenfilter
Trying https://github.com/mobz/elasticsearch-head/archive/master.zip...
Downloading ..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Installed mobz/elasticsearch-head into f:\PHOTON\photon_data\elasticsearch\plugins\head
Trying https://github.com/polyfractal/elasticsearch-inquisitor/archive/master.zip...
Downloading ..............................................................................................................................................................................................DONE
Installed polyfractal/elasticsearch-inquisitor into f:\PHOTON\photon_data\elasticsearch\plugins\inquisitor
[main] INFO org.elasticsearch.node - [Condor] version[1.7.0], pid[53436], build[929b973/2015-07-16T14:31:07Z]
[main] INFO org.elasticsearch.node - [Condor] initializing ...
[main] INFO org.elasticsearch.plugins - [Condor] loaded [wordending], sites [head, inquisitor]
[main] INFO org.elasticsearch.env - [Condor] using [1] data paths, mounts [[LocalData2 (F:)]], net usable_space [386.8gb], net total_space [931.3gb], types [NTFS]
[main] WARN org.elasticsearch.bootstrap - JNA not found. native methods will be disabled.
[main] WARN org.elasticsearch.script - [Condor] deprecated setting [script.disable_dynamic] is set, replace with fine-grained scripting settings (e.g. script.inline, script.indexed, script.file)
[main] INFO org.elasticsearch.script - [Condor] compiling script file [f:\PHOTON\photon_data\elasticsearch\config\scripts\general-score.groovy]
[main] INFO org.elasticsearch.script - [Condor] compiling script file [f:\PHOTON\photon_data\elasticsearch\config\scripts\location-biased-score.groovy]
[main] ERROR org.elasticsearch.gateway.local.state.shards - [Condor] failed to read local state (started shards), exiting...
[main] ERROR org.elasticsearch.gateway.local.state.meta - [Condor] failed to read local state, exiting...
[main] ERROR org.elasticsearch.gateway.local.state.shards - [Condor] failed to read local state (started shards), exiting...
[main] ERROR org.elasticsearch.gateway.local.state.meta - [Condor] failed to read local state, exiting...
[main] ERROR org.elasticsearch.gateway.local.state.shards - [Condor] failed to read local state (started shards), exiting...
[main] ERROR org.elasticsearch.gateway.local.state.meta - [Condor] failed to read local state, exiting...
Exception in thread "main" org.elasticsearch.common.inject.CreationException: Guice creation errors:

**1) Error injecting constructor, org.elasticsearch.ElasticsearchException: Format version is not supported (resource: SimpleFSIndexInput(path="F:\PHOTON\photon_data\elasticsearch\data\photon\nodes\0\_state\global-0.st")): 1 (needs to be between 0 and 0)**
  at org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState.<init>(Unknown Source)
  while locating org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState
    for parameter 4 at org.elasticsearch.gateway.local.LocalGateway.<init>(Unknown Source)
  while locating org.elasticsearch.gateway.local.LocalGateway
  while locating org.elasticsearch.gateway.Gateway
    for parameter 1 at org.elasticsearch.gateway.GatewayService.<init>(Unknown Source)
  while locating org.elasticsearch.gateway.GatewayService
Caused by: org.elasticsearch.ElasticsearchException: Format version is not supported (resource: SimpleFSIndexInput(path="F:\PHOTON\photon_data\elasticsearch\data\photon\nodes\0\_state\global-0.st")): 1 (needs to be between 0 and 0)
        at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:153)
        at org.elasticsearch.gateway.local.state.meta.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:297)
        at org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState.loadGlobalState(LocalGatewayMetaState.java:404)
        at org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState.loadState(LocalGatewayMetaState.java:378)
        at org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState.<init>(LocalGatewayMetaState.java:164)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
        at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:210)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
        at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:166)
        at de.komoot.photon.elasticsearch.Server.start(Server.java:118)
        at de.komoot.photon.App.main(App.java:46)
Caused by: org.elasticsearch.gateway.local.state.meta.CorruptStateException: Format version is not supported (resource: SimpleFSIndexInput(path="F:\PHOTON\photon_data\elasticsearch\data\photon\nodes\0\_state\global-0.st")): 1 (needs to be between 0 and 0)
        at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:156)
        at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:138)
        at org.elasticsearch.gateway.local.state.meta.MetaDataStateFormat.read(MetaDataStateFormat.java:169)
        at org.elasticsearch.gateway.local.state.meta.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:287)
        ... 48 more

2) Error injecting constructor, org.elasticsearch.ElasticsearchException: Format version is not supported (resource: SimpleFSIndexInput(path="F:\PHOTON\photon_data\elasticsearch\data\photon\nodes\0\_state\global-0.st")): 1 (needs to be between 0 and 0)
  at org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState.<init>(Unknown Source)
  while locating org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState
    for parameter 4 at org.elasticsearch.gateway.local.LocalGateway.<init>(Unknown Source)
  while locating org.elasticsearch.gateway.local.LocalGateway
  while locating org.elasticsearch.gateway.Gateway
Caused by: org.elasticsearch.ElasticsearchException: Format version is not supported (resource: SimpleFSIndexInput(path="F:\PHOTON\photon_data\elasticsearch\data\photon\nodes\0\_state\global-0.st")): 1 (needs to be between 0 and 0)
        at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:153)
        at org.elasticsearch.gateway.local.state.meta.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:297)
        at org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState.loadGlobalState(LocalGatewayMetaState.java:404)
        at org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState.loadState(LocalGatewayMetaState.java:378)
        at org.elasticsearch.gateway.local.state.meta.LocalGatewayMetaState.<init>(LocalGatewayMetaState.java:164)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
        at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:210)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
        at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:166)
        at de.komoot.photon.elasticsearch.Server.start(Server.java:118)
        at de.komoot.photon.App.main(App.java:46)
Caused by: org.elasticsearch.gateway.local.state.meta.CorruptStateException: Format version is not supported (resource: SimpleFSIndexInput(path="F:\PHOTON\photon_data\elasticsearch\data\photon\nodes\0\_state\global-0.st")): 1 (needs to be between 0 and 0)
        at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:156)
        at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:138)
        at org.elasticsearch.gateway.local.state.meta.MetaDataStateFormat.read(MetaDataStateFormat.java:169)
        at org.elasticsearch.gateway.local.state.meta.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:287)
        ... 39 more

[...]

Regards
Raul

**Comment by karussell** [comment]
Question should go to the mailing list. And it is important to use the data named in the readme (photon-db-latest.tar.bz2)!
