### ISSUE TITLE
update lombok or make jdk9 compatible

### ISSUE THREAD

**Issue by karussell** [komoot/photon#274]
For our  jdk9 builds we get an error:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by lombok.javac.apt.Processor (file:/home/travis/.m2/repository/org/projectlombok/lombok/1.12.6/lombok-1.12.6.jar) to field com.sun.tools.javac.processing.JavacProcessingEnvironment.processorClassLoader
```

**Comment by karussell** [comment]
Updating lombok improved the situation but still some powermock problems:

```
Caused by: java.lang.IllegalAccessError: class jdk.internal.reflect.ConstructorAccessorImpl loaded by org/powermock/core/classloader/MockClassLoader cannot access jdk/internal/reflect superclass jdk.internal.reflect.MagicAccessorImpl
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
	at org.powermock.core.classloader.MockClassLoader.loadUnmockedClass(MockClassLoader.java:238)
```

And

```
Running de.komoot.photon.searcher.ElasticsearchSearcherFactoryTest
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mockito.cglib.core.ReflectUtils$2 (file:/home/travis/.m2/repository/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.mockito.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.42 sec
```

Results:

```
Tests in error: 
  initializationError(de.komoot.photon.ReverseSearchRequestHandlerTest): java.lang.reflect.InvocationTargetException
  initializationError(de.komoot.photon.SearchRequestHandlerTest): java.lang.reflect.InvocationTargetException
```
