### ISSUE TITLE
Problem with new extracts

### ISSUE THREAD

**Issue by karussell** [komoot/photon#283]
@christophlingg reported on the mailing list:

```
the photon public api photon.komoot.de/api/q=berlin is not working any more. I guessed it is related to the new data updates requiring to use photon 0.3. I tried to use the alpha version (photon-0.3-alpha1.jar) from github. I still get an exception though:

Exception in thread "main" java.lang.IllegalArgumentException: property [elasticsearch.version] is missing for plugin [elasticsearch-inquisitor]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:135)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:331)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:130)
        at org.elasticsearch.node.Node.<init>(Node.java:312)
        at de.komoot.photon.elasticsearch.Server$MyNode.<init>(Server.java:59)
        at de.komoot.photon.elasticsearch.Server.start(Server.java:119)
        at de.komoot.photon.App.main(App.java:52)

The plugins are part of the data dumps if i recall correctly. Any idea what I can do to fix that
```

**Comment by karussell** [comment]
@christophlingg maybe running the old jar made the data somehow corrupt? (creating plugin folder with empty version stuff)

**Comment by karussell** [comment]
I cannot reproduce this with the latest master nor 3.0-alpha1 and the current data snapshot from November (btw: in a few hours a snapshot for January will be out)

**Comment by dooley** [comment]
Someone looking into this issue? The public api as well as the search on the demopage https://photon.komoot.de/ seems to be down since at least today morning.

```
https://photon.komoot.de/api/?q=berlin > returns status 502 Bad Gateway with a 404-Errorpage.
```

**Comment by karussell** [comment]
Please see the discussion on the mailing list: https://lists.openstreetmap.org/pipermail/photon/2018-January/000094.html

**Comment by itschrake** [comment]
Hi Dooley, 
first of all thank you and all of your colleagues very much for providing photon. It is a very usefull tool and we really love using it.
This may be a repost but can you tell wether and when the public API will be working again? Best regards and many thanks, Paul

**Comment by karussell** [comment]
Is now fixed

**Comment by christophlingg** [comment]
hi guys, the api is up again. it is now based on the brand-new version 0.3.
