### ISSUE TITLE
ResourceAlreadyExistsException on recreate-index

### ISSUE THREAD

**Issue by hbruch** [komoot/photon#292]
When trying to recreate an already existing index, a ResourceAlreadyExistsException is thrown:

018-01-12 11:23:56,702 [main] INFO  de.komoot.photon.elasticsearch.Server - started elastic search node
Exception in thread "main" [photon/zMD-dGQcS060DYPGJdE4gg] ResourceAlreadyExistsException[index [photon/zMD-dGQcS060DYPGJdE4gg] already exists]
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:147)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:495)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$000(MetaDataCreateIndexService.java:106)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:239)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
	at org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:634)
	at org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:612)
	at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:571)
	at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mumins** [comment]
I have a similar issue when trying to update photon index from nominatim database.

Photon release: https://github.com/komoot/photon/releases/download/0.3-beta3/photon-0.3-beta3.jar
Photon data: http://download1.graphhopper.com/public/photon-db-nl-180226.tar.bz2
Nominatim release: v3.1.0-55-gd79a2bb
Nominatim data: http://download.geofabrik.de/europe/netherlands-latest.osm.pbf on 23/03/2018

Command:
 java -jar photon-0.3-beta3.jar -nominatim-import -host x.x.x.x -port 5432 -database nominatim -user photon_updater -password ***** -languages en,de,fr,it,es,pl,ro,nl,hu,pt,el,sv,cs,bg,sk,da,fi,lt,sl,et,hr,ga,lv,mt

Error:
2018-03-27 11:26:48,992 [elasticsearch[Ay2iz-W][generic][T#5]] WARN  org.elasticsearch.cluster.action.shard.ShardStateAction - [photon][3] unexpected failure while sending request [internal:cluster/shard/started] to [{Ay2iz-W}{Ay2iz-WZT3eZMlommmHF5w}{wVeOivhaQSeY4KaJngqy2g}{127.0.0.1}{127.0.0.1:9300}] for shard entry [shard id [[photon][3]], allocation id [YdBGn5emSw6Dn_NK91iHCA], primary term [0], message [after existing recovery]]
org.elasticsearch.transport.SendRequestTransportException: [Ay2iz-W][127.0.0.1:9300][internal:cluster/shard/started]
        at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:596) ~[photon-0.3-beta3.jar:?]
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:519) ~[photon-0.3-beta3.jar:?]
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:494) ~[photon-0.3-beta3.jar:?]
        at org.elasticsearch.cluster.action.shard.ShardStateAction.sendShardAction(ShardStateAction.java:104) ~[photon-0.3-beta3.jar:?]
        at org.elasticsearch.cluster.action.shard.ShardStateAction.shardStarted(ShardStateAction.java:360) ~[photon-0.3-beta3.jar:?]
        at org.elasticsearch.cluster.action.shard.ShardStateAction.shardStarted(ShardStateAction.java:356) ~[photon-0.3-beta3.jar:?]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService$RecoveryListener.onRecoveryDone(IndicesClusterStateService.java:625) ~[photon-0.3-beta3.jar:?]
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$2(IndexShard.java:1488) ~[photon-0.3-beta3.jar:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) ~[photon-0.3-beta3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: org.elasticsearch.transport.TransportException: TransportService is closed stopped can't send request
        at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:580) ~[photon-0.3-beta3.jar:?]
        ... 11 more

**Comment by karussell** [comment]
Updating an index is not a good idea because it is difficult to exclude duplicates. We should throw an exception ... but probably a more descriptive one ;)

**Comment by phpia** [comment]
@kurko Do not remove ./photon_data
Instead remove photon_data/elasticsearch/data

**Comment by lonvia** [comment]
A reimport simply drops the existing database these days.
