### ISSUE TITLE
photon fails to start when path contains spaces

### ISSUE THREAD

**Issue by thunder39** [komoot/photon#315]
Hi,

If I start photon with java -jar photon-0.3-beta3.jar from a path which contains spaces e.g: "C:\Program Files\photon" it fails with the exception:

Exception in thread "main" java.lang.RuntimeException: Can't create directories:
        at de.komoot.photon.elasticsearch.Server.<init>(Server.java:71)
        at de.komoot.photon.elasticsearch.Server.<init>(Server.java:60)
        at de.komoot.photon.App.main(App.java:47)
Caused by: java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/photon/.
        at java.net.URI$Parser.fail(Unknown Source)
        at java.net.URI$Parser.checkChars(Unknown Source)
        at java.net.URI$Parser.parseHierarchical(Unknown Source)
        at java.net.URI$Parser.parse(Unknown Source)
        at java.net.URI.<init>(Unknown Source)
        at java.net.URL.toURI(Unknown Source)
        at de.komoot.photon.elasticsearch.Server.setupDirectories(Server.java:149)
        at de.komoot.photon.elasticsearch.Server.<init>(Server.java:66)
        ... 2 more

Tested on Windows Server 2012 R2.

Let me know if you need any additional info!

**Comment by karussell** [comment]
Good question why we use a URI there. Does not make sense to me. If you can try the following 2 changes:

setupDirectories(new File(mainDirectory));

and

private void setupDirectories(final File mainDirectory) throws IOException, URISyntaxException {

this would be appreciated
