### ISSUE TITLE
IllegalArgumentException should not result in http error code 500

### ISSUE THREAD

**Issue by karussell** [komoot/photon#350]
If we request `/reverse?point=-14.307135835180144%2C181.90355300903323` the longitude is invalid and it is a bad request and should result in a 400 error code but currently is a 500 one.

```
2018-07-31 23:16:59,498 [qtp231387735-195899] ERROR spark.http.matching.GeneralError - 
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:272) ~[photon-0.2.9-SNAPSHOT.jar:?]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:130) ~[photon-0.2.9-SNAPSHOT.jar:?]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:241) ~[photon-0.2.9-SNAPSHOT.jar:?]
....
Caused by: org.elasticsearch.index.query.QueryShardException: couldn't validate latitude/ longitude values
	at org.elasticsearch.index.query.GeoDistanceQueryBuilder.doToQuery(GeoDistanceQueryBuilder.java:293) ~[photon-0.2.9-SNAPSHOT.jar:?]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[photon-0.2.9-SNAPSHOT.jar:?]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toFilter(AbstractQueryBuilder.java:118) ~[photon-0.2.9-SNAPSHOT.jar:?]
	at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:448) ~[photon-0.2.9-SNAPSHOT.jar:?]
	at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:421) ~[photon-0.2.9-SNAPSHOT.jar:?]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[photon-0.2.9-SNAPSHOT.jar:?]
...
Caused by: java.lang.IllegalArgumentException: Validation Failed: 1: [geo_distance] center point longitude is invalid: 181.90355300903323;
	at org.elasticsearch.index.query.QueryValidationException.addValidationError(QueryValidationException.java:42) ~[photon-0.2.9-SNAPSHOT.jar:?]
	at org.elasticsearch.index.query.AbstractQueryBuilder.addValidationError(AbstractQueryBuilder.java:165) ~[photon-0.2.9-SNAPSHOT.jar:?]
	at org.elasticsearch.index.query.GeoDistanceQueryBuilder.checkLatLon(GeoDistanceQueryBuilder.java:488) ~[photon-0.2.9-SNAPSHOT.jar:?]
	at org.elasticsearch.index.query.GeoDistanceQueryBuilder.doToQuery(GeoDistanceQueryBuilder.java:291) ~[photon-0.2.9-SNAPSHOT.jar:?]

```

**Comment by hbruch** [comment]
Not sure if this is only the case for the GraphHopper implementation, as [ReverseRequestFactory](https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/query/ReverseRequestFactory.java#L40) does such a validation. However, for the location_bias in forward geocoding, this is not done yet.

I'll add the verification for this as well.

**Comment by karussell** [comment]
Ups, this could be. Will be time that I implement a simple filter to do the conversion.
