### ISSUE TITLE
Error while importing nominatim database already exists 

### ISSUE THREAD

**Issue by mbutler-79** [komoot/photon#359]
Hi,
please let me know how to fix this issue, when I run this command, I get this error:
sudo java -jar photon-0.3.0.jar -nominatim-import -host localhost -port 5432 -database nominatim -user nominatim -password ******

result of above command:
2018-09-24 12:44:55,766 [main] WARN  org.elasticsearch.node.Node - version [5.5.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
2018-09-24 12:45:01,470 [main] INFO  de.komoot.photon.elasticsearch.Server - started elastic search node
2018-09-24 12:45:02,162 [main] INFO  de.komoot.photon.elasticsearch.Server - mapping created: {"place":{"dynamic":"false","_source":{"excludes":["context.*"]},"_all":{"enabled":false},"properties":{"osm_id":{"type":"long"},"country":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text"},"default":{"copy_to":["collector.default"],"index":false,"type":"text"},"en":{"copy_to":["collector.en"],"index":false,"type":"text"},"it":{"copy_to":["collector.it"],"index":false,"type":"text"},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text"}}},"coordinate":{"type":"geo_point"},"city":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text"},"default":{"copy_to":["collector.default"],"index":false,"type":"text"},"en":{"copy_to":["collector.en"],"index":false,"type":"text"},"it":{"copy_to":["collector.it"],"index":false,"type":"text"},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text"}}},"importance":{"type":"float"},"postcode":{"copy_to":["collector.default"],"index":false,"type":"text"},"collector":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"default":{"analyzer":"index_ngram","type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"}}},"en":{"copy_to":["collector.en"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"it":{"copy_to":["collector.it"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}}}},"osm_type":{"index":false,"type":"text"},"osm_key":{"index":true,"type":"keyword"},"housenumber":{"copy_to":["collector.default"],"search_analyzer":"standard","analyzer":"index_housenumber","index":true,"type":"text"},"street":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text"},"default":{"copy_to":["collector.default"],"index":false,"type":"text"},"en":{"copy_to":["collector.en"],"index":false,"type":"text"},"it":{"copy_to":["collector.it"],"index":false,"type":"text"},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text"}}},"context":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text"},"default":{"copy_to":["collector.default"],"index":false,"type":"text"},"en":{"copy_to":["collector.en"],"index":false,"type":"text"},"it":{"copy_to":["collector.it"],"index":false,"type":"text"},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text"}}},"name":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"loc":{"copy_to":["collector.default"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"}}},"default":{"copy_to":["collector.default","name.en","name.de","name.fr","name.it","name.en","name.fr","name.de","name.it"],"index":false,"type":"text"},"reg":{"copy_to":["collector.default"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"}}},"old":{"copy_to":["collector.default"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"}}},"alt":{"copy_to":["collector.default"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"}}},"en":{"copy_to":["collector.en"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"it":{"copy_to":["collector.it"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"int":{"copy_to":["collector.default"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"}}}}},"osm_value":{"index":true,"type":"keyword"},"state":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text"},"default":{"copy_to":["collector.default"],"index":false,"type":"text"},"en":{"copy_to":["collector.en"],"index":false,"type":"text"},"it":{"copy_to":["collector.it"],"index":false,"type":"text"},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text"}}}}}}
2018-09-24 12:45:02,163 [main] INFO  de.komoot.photon.App - starting import from nominatim to photon with languages: en,fr,de,it
2018-09-24 12:45:02,200 [main] INFO  de.komoot.photon.nominatim.NominatimConnector - start importing documents from nominatim (global)
Exception in thread "main" org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "nominatim")
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:386)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:466)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:471)
	at de.komoot.photon.nominatim.NominatimConnector.readEntireDatabase(NominatimConnector.java:341)
	at de.komoot.photon.App.startNominatimImport(App.java:124)
	at de.komoot.photon.App.main(App.java:59)
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "nominatim")
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
	... 6 more
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "nominatim"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at org.postgis.jts.JtsWrapper.connect(JtsWrapper.java:89)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	... 10 more

**Comment by gopi-ar** [comment]
`FATAL: password authentication failed for user "nominatim"`

Have you added password based auth for this user?

**Comment by mbutler-79** [comment]
I set password again:
ALTER USER nominatim WITH ENCRYPTED PASSWORD *******;

and again run this command:
sudo java -jar photon-0.3.0.jar -nominatim-import -host localhost -port 5432 -database nominatim -user nominatim -password *****

I think it`s working, not getting any error yet
it seems it`s working correct?
