### ISSUE TITLE
not updating photon by updated nominatim data

### ISSUE THREAD

**Issue by mbutler-79** [komoot/photon#415]
Hi,
I have a problem with photon. I had already imported data to nominatim db. 
afterwards, I imported data to photon based on new imported data from nominatim.
but for some reason I was forced to empty nominatim db and imported new data to it, and then updated photon. but the problem is that there is old indexed data on photon yet.
I thought that by this command is updated photon data :
        curl http://localhost:2322/nominatim-update

I saw this error after running this command :
```java
Exception in thread "Thread-200" org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: no requests added;
	at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:29)
	at org.elasticsearch.action.bulk.BulkRequest.validate(BulkRequest.java:600)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:131)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:84)
	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83)
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at de.komoot.photon.elasticsearch.Updater.updateDocuments(Updater.java:64)
	at de.komoot.photon.elasticsearch.Updater.finish(Updater.java:30)
	at de.komoot.photon.nominatim.NominatimUpdater.update(NominatimUpdater.java:65)
	at de.komoot.photon.App.lambda$null$0(App.java:152)
	at java.lang.Thread.run(Thread.java:748)
```
but seems this command doesn`t work correctly.
please let me know how can i fix this issue?

**Comment by lonvia** [comment]
The error basically tells you that there is no data to update. This is expected. The update command is only to be used when applying updates to the Nominatim database. If you reimport your Nominatim database, you also have to recreate the hpoton database. Simply delete the `photon_data` directory and start a new import.
