### ISSUE TITLE
nominatim-import issue with AWS Elasticsearch

### ISSUE THREAD

**Issue by xydinesh** [komoot/photon#435]
I'm trying to import data into an AWS managed elasticsearch instance using `nominatim-import` option. I'm getting following error,

```

 java -jar photon-*.jar -nominatim-import -host localhost -port 5432 -database nominatim -user nominatim -transport-addresses vpc-pelias-es-3z2pteolfkhk46bzmqsq6fqsha.us-east-1.es.amazonaws.com
2019-09-24 21:52:59,733 [main] INFO  de.komoot.photon.elasticsearch.Server - started elastic search client connected to [vpc-pelias-es-3z2pteolfkhk46bzmqsq6fqsha.us-east-1.es.amazonaws.com]
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{-dGTbO7pRpmrT5WNm10ubw}{vpc-pelias-es-3z2pteolfkhk46bzmqsq6fqsha.us-east-1.es.amazonaws.com}{10.204.0.45:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1256)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
        at de.komoot.photon.elasticsearch.Server.deleteIndex(Server.java:200)
        at de.komoot.photon.elasticsearch.Server.recreateIndex(Server.java:178)
        at de.komoot.photon.App.startNominatimImport(App.java:115)
        at de.komoot.photon.App.main(App.java:59)
```

I appreciate any ideas on how to solve this.

**Comment by xydinesh** [comment]
According to this issue, https://stackoverflow.com/questions/33412635/how-to-connect-to-aws-elasticsearch

AWS only supports REST Client access to the cluster. If we can add an option to use REST client this should work. Let me know if you see an easy way to fix this.

**Comment by karussell** [comment]
We won't support AWS Elasticsearch. If you like, do not hesitate to create a pull request.
