### ISSUE TITLE
ERROR: relation "placex" does not exist

### ISSUE THREAD

**Issue by ParasQ** [komoot/photon#476]
Hi,
I have installed Nominatim database and its working on localhost, But not able to import database to photon. Please help to resolve this.

 Showing error: At de.komoot.photon.nominatim.NominatimConnector
Exception in thread "main" org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT place_id, osm_type, osm_id, class, type, name, housenumber, postcode, extratags, ST_Envelope(geometry) AS bbox, parent_place_id, linked_place_id, rank_search, importance, country_code, centroid FROM placex WHERE linked_place_id IS NULL AND centroid IS NOT NULL ORDER BY geometry_sector; ]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "placex" does not exist

Full logs;
2020-06-22 07:10:55,085 [main] WARN org.elasticsearch.node.Node - version [5.5.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production

2020-06-22 07:10:59,929 [main] INFO de.komoot.photon.elasticsearch.Server - started elastic search node

2020-06-22 07:11:01,330 [main] INFO de.komoot.photon.elasticsearch.Server - mapping created: {"place":{"dynamic":"false","_source":{"excludes":["context.*"]},"_all":{"enabled":false},"properties":{"osm_id":{"type":"long"},"country":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text"},"default":{"copy_to":["collector.default"],"index":false,"type":"text"},"en":{"copy_to":["collector.en"],"index":false,"type":"text"},"it":{"copy_to":["collector.it"],"index":false,"type":"text"},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text"}}},"coordinate":{"type":"geo_point"},"city":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text"},"default":{"copy_to":["collector.default"],"index":false,"type":"text"},"en":{"copy_to":["collector.en"],"index":false,"type":"text"},"it":{"copy_to":["collector.it"],"index":false,"type":"text"},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text"}}},"importance":{"type":"float"},"countrycode":{"index":false,"type":"text"},"postcode":{"copy_to":["collector.default"],"index":false,"type":"text"},"collector":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"default":{"analyzer":"index_ngram","type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"}}},"en":{"copy_to":["collector.en"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"it":{"copy_to":["collector.it"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}}}},"osm_type":{"index":false,"type":"text"},"osm_key":{"index":true,"type":"keyword"},"housenumber":{"copy_to":["collector.default"],"search_analyzer":"standard","analyzer":"index_housenumber","index":true,"type":"text"},"street":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text"},"default":{"copy_to":["collector.default"],"index":false,"type":"text"},"en":{"copy_to":["collector.en"],"index":false,"type":"text"},"it":{"copy_to":["collector.it"],"index":false,"type":"text"},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text"}}},"context":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text"},"default":{"copy_to":["collector.default"],"index":false,"type":"text"},"en":{"copy_to":["collector.en"],"index":false,"type":"text"},"it":{"copy_to":["collector.it"],"index":false,"type":"text"},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text"}}},"name":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"loc":{"copy_to":["collector.default"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"}}},"default":{"copy_to":["collector.default","name.en","name.de","name.fr","name.it","name.en","name.fr","name.de","name.it"],"index":false,"type":"text"},"reg":{"copy_to":["collector.default"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"}}},"old":{"copy_to":["collector.default"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"}}},"alt":{"copy_to":["collector.default"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"}}},"en":{"copy_to":["collector.en"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"it":{"copy_to":["collector.it"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"},"ngrams":{"analyzer":"index_ngram","type":"text"}}},"int":{"copy_to":["collector.default"],"index":false,"type":"text","fields":{"raw":{"analyzer":"index_raw","type":"text"}}}}},"osm_value":{"index":true,"type":"keyword"},"state":{"properties":{"de":{"copy_to":["collector.de"],"index":false,"type":"text"},"default":{"copy_to":["collector.default"],"index":false,"type":"text"},"en":{"copy_to":["collector.en"],"index":false,"type":"text"},"it":{"copy_to":["collector.it"],"index":false,"type":"text"},"fr":{"copy_to":["collector.fr"],"index":false,"type":"text"}}}}}}

2020-06-22 07:11:01,330 [main] INFO de.komoot.photon.App - starting import from nominatim to photon with languages: en,fr,de,it

2020-06-22 07:11:01,409 [main] INFO de.komoot.photon.nominatim.NominatimConnector - start importing documents from nominatim (global)

Jun 22, 2020 7:11:01 AM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions

INFO: Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]

Jun 22, 2020 7:11:01 AM org.springframework.jdbc.support.SQLErrorCodesFactory <init>

INFO: SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase]

Exception in thread "main" org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT place_id, osm_type, osm_id, class, type, name, housenumber, postcode, extratags, ST_Envelope(geometry) AS bbox, parent_place_id, linked_place_id, rank_search, importance, country_code, centroid FROM placex WHERE linked_place_id IS NULL AND centroid IS NOT NULL ORDER BY geometry_sector; ]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "placex" does not exist

Position: 207

at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231)

at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)

at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:411)

at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:466)

at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:471)

at de.komoot.photon.nominatim.NominatimConnector.readEntireDatabase(NominatimConnector.java:361)

at de.komoot.photon.App.startNominatimImport(App.java:128)

at de.komoot.photon.App.main(App.java:63)

Caused by: org.postgresql.util.PSQLException: ERROR: relation "placex" does not exist

Position: 207

at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103)

at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)

at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)

at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)

at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)

at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:254)

at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)

at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)

at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:450)

at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:400)

**Comment by lonvia** [comment]
This looks like you try to access the wrong database. Please provide the command line you use for photon.

**Comment by lonvia** [comment]
Closing as no further feedback was provided.
