### ISSUE TITLE
SocketTimeoutException connecting with Nominatim database in docker container

### ISSUE THREAD

**Issue by dbGilges** [komoot/photon#560]
My environment:

- macOS Catalina Version 10.15.7
- [nominatim-docker](https://github.com/mediagis/nominatim-docker) for nominatim

I use [nominatim-docker](https://github.com/mediagis/nominatim-docker) to start nominatim in a container. I want to import data to Photon because I want to limit the dataset to my country only. So I typed in this:

`java -jar photon-0.3.4.jar -nominatim-import -host 172.17.0.2 -port 5432 -database nominatim -user nominatim -password sUpErSeCrEt -languages de`

This is the result:

```
2021-04-07 22:02:01,428 [main] INFO  de.komoot.photon.nominatim.NominatimConnector - start importing documents from nominatim (global)
Exception in thread "main" org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (Der Verbindungsversuch schlug fehl.)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:82)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:457)
	at de.komoot.photon.nominatim.NominatimConnector.readEntireDatabase(NominatimConnector.java:358)
	at de.komoot.photon.App.startNominatimImport(App.java:138)
	at de.komoot.photon.App.main(App.java:63)
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (Der Verbindungsversuch schlug fehl.)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	... 6 more
Caused by: org.postgresql.util.PSQLException: Der Verbindungsversuch schlug fehl.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:297)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:459)
	at org.postgresql.Driver.connect(Driver.java:261)
	at org.postgis.jts.JtsWrapper.connect(JtsWrapper.java:94)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665)
	... 11 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at org.postgresql.core.PGStream.<init>(PGStream.java:81)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:93)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:197)
	... 20 more

```

Is this a bug or is there anything else I can do to prevent this error to happen?

**Comment by lonvia** [comment]
As the message says: photon can't connect to the Nominatim server. That is not a bug in Photon but an issue with your docker setup. I'm sorry but we can't give support on docker administration here. I'll move the ticket into the discussion section. Maybe some other Photon user is willing to help.
