### ISSUE TITLE
`java.lang.NullPointerException` of NominatimConnector when try to update index from nominatim

### ISSUE THREAD

**Issue by JinIgarashi** [komoot/photon#562]
We updated nominatim database by using below command.

```
$ ./utils/update.php --no-npi --import-osmosis --no-index 
```

Then, we tried to execute the following command to update photon index from our nominatim database

```
$ java photon.jar -nominatim-update -host localhost-port 5432-database nominatim -user nominatim -password $NOMINATIM_PASSWORD -languages en,ja,ja_kana
```

However, there was `NullPointerException` at `NominatimConnector.java`.

```
2021-04-12 01:36:38,500 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 1
2021-04-12 01:36:38,890 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 2
2021-04-12 01:36:38,980 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 3
2021-04-12 01:36:39,067 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 4
2021-04-12 01:36:39,148 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 5
2021-04-12 01:36:39,150 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 6
2021-04-12 01:36:39,225 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 7
2021-04-12 01:36:39,296 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 8
2021-04-12 01:36:39,368 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 9
2021-04-12 01:36:39,370 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 10
2021-04-12 01:36:39,440 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 11
2021-04-12 01:36:39,506 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 12
2021-04-12 01:36:39,580 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 13
2021-04-12 01:36:39,644 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 14
2021-04-12 01:36:39,716 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 15
2021-04-12 01:36:39,783 [Thread-9] INFO  de.komoot.photon.nominatim.NominatimUpdater - Starting rank 16
Exception in thread "Thread-9" java.lang.NullPointerException
        at de.komoot.photon.nominatim.NominatimConnector.getByPlaceId(NominatimConnector.java:152)
        at de.komoot.photon.nominatim.NominatimUpdater.update(NominatimUpdater.java:69)
        at de.komoot.photon.App.lambda$startApi$1(App.java:185)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

We also tried to update through update api like below. But there was the same NullPointer error with above.

```
$ java photon.jar  -host localhost-port 5432-database nominatim -user nominatim -password $NOMINATIM_PASSWORD -languages en,ja,ja_kana
$ curl http://localhost:2322/nominatim-update
nominatim update started (more information in console output)
```

Is there any idea for this error?

**Comment by lonvia** [comment]
Are you on latest master. This should have been fixed with #558.

**Comment by JinIgarashi** [comment]
@lonvia Thanks a lot! I will merge the latest master into our branch and try it again! Then I will let you know the result.

**Comment by JinIgarashi** [comment]
now, there is no error occurred. I close this issue now. Thanks.
