### ISSUE TITLE
language italian problems

### ISSUE THREAD

**Issue by eroslink** [komoot/photon#783]
With versions 0.4.4 and 0.5.0, when using Italian language, this error occurs..

root@pc-xxx /h/photongit (master)# java -jar photon-*.jar -languages it
2024-03-06 16:57:01,579 [main] WARN  org.elasticsearch.node.Node - version [5.6.16-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/home/photongit/photon-0.5.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2024-03-06 16:57:08,890 [main] INFO  de.komoot.photon.elasticsearch.Server - Started elastic search node
2024-03-06 16:57:08,890 [main] INFO  de.komoot.photon.App - Make sure that the ES cluster is ready, this might take some time.
2024-03-06 16:57:11,710 [main] INFO  de.komoot.photon.App - ES cluster is now ready.
Exception in thread "main" java.lang.RuntimeException: Language list '[it]' not compatible with languages in database([en, de, fr])
        at de.komoot.photon.DatabaseProperties.restrictLanguages(DatabaseProperties.java:66)
        at de.komoot.photon.App.startApi(App.java:176)
        at de.komoot.photon.App.main(App.java:65)

**Comment by mtmail** [comment]
Did you download the search index described in https://github.com/komoot/photon?tab=readme-ov-file#installation or create your own? The downloaded one doesn't contain the Italian language.

**Comment by eroslink** [comment]
i downloaded this wget -O - https://download1.graphhopper.com/public/photon-db-latest.tar.bz2 | pbzip2 -cd | tar x
in 0.3.4 this run

**Comment by mtmail** [comment]
Read the documentation again. That file does not contain Italian language.
